### ISSUE TITLE
📢 m2-d2 has missing media

### ISSUE THREAD

**Issue by ubeytd** [Reniejr/Homeworks-M2#1]
Your m2-d2 music project has missing media, it is causing a loading issue

thus we are not able to see your project 

`intro.src = 'Logo RJD Developer.mp4'`

this media file is not on Github please fix this.

**Comment by Reniejr** [comment]
Oh yes for sure, i am gonna take it out cause it is not complete yet the
intro animation

**Comment by ubeytd** [comment]
Great! You can close this issue when you finish fix. ✔
